### ISSUE TITLE
fails to detect a tunnel

### ISSUE THREAD

**Issue by netllama** [nojhan/tunnelmon#2]
First time attempting to use this tool, and its failing to detect a working tunnel:
```
[netllama@hal tunnelmon-1.0]$ ./tunnelmon.py 
TYPE	SSH_PID	IN_PORT	VIA_HOST	TARGET_HOST	OUT_PORT
[netllama@hal tunnelmon-1.0]$ ps -ef | grep autossh
root     1634439 1633647  0 16:14 pts/2    00:00:00 nedit /usr/lib/systemd/system/autossh@dv-ssh.service
netllama 1638649       1  0 16:28 ?        00:00:00 /usr/bin/autossh -M 0 -o ExitOnForwardFailure=yes -NTR 2220:127.0.0.1:22 netllama@example.com-i /home/netllama/.ssh/id_ed25519
```

**Comment by nojhan** [comment]
Thank you for your interest in this small free software.

Can you tell which operating system you are using?
I would also need to see the logs, which you can get by appending the `--log-level debug` to the faulty command.
Thanks for your help!

**Comment by netllama** [comment]
I'm using Linux on both systems:
```
$ ./tunnelmon.py --log-level debug
DEBUG:root:----- Started Ereshkigal -----
DEBUG:root:Log to stdout
DEBUG:root:Asked for: {'curses': False, 'connections': False, 'tunnels': False, 'log_level': 'debug', 'log_file': None, 'config_file': None}
DEBUG:root:Entering default mode
DEBUG:root:{'ppid': 1661824, 'cmdline': ['/usr/bin/ssh', '-o', 'ExitOnForwardFailure=yes', '-NTR', '2220:127.0.0.1:22', '-i', '/home/netllama/.ssh/id_ed25519', 'netllama@example.com'], 'connections': [pconn(fd=3, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='10.0.0.1', port=46150), raddr=addr(ip='a.b.c.d', port=22), status='ESTABLISHED')], 'pid': 1844939, 'name': 'ssh'}
DEBUG:root:autossh cmd line: /usr/bin/ssh -o ExitOnForwardFailure=yes -NTR 2220:127.0.0.1:22 -i /home/netllama/.ssh/id_ed25519 netllama@example.com
DEBUG:root:forwarding regexp: re.compile('-L\\s*(\\d+):(.*):(\\d+)')
DEBUG:root:[]
DEBUG:root:OrderedDict()
TYPE	SSH_PID	IN_PORT	VIA_HOST	TARGET_HOST	OUT_PORT
```

Based on the above output, its definitely finding the tunnel, but then not using it?

**Comment by netllama** [comment]
Actually, I see the problem, its expecting local forwarding (-L), but I'm doing remote forwarding (-R).

**Comment by nojhan** [comment]
See, the regexp responsible for matching processes is looking for local
port forwarding `-L` but you use remote port forwarding.
I don't have an easy access to a dev station right now, but if you just
edit the regexp it should do the trick.
Technically, I suppose replacing `-L` by `-[LRD]` should be enough.

**Comment by netllama** [comment]
Actually, that solution is insufficient as well.  My command is `-NTR 2220:127.0.0.1:22` so even if it matches [LRD] it won't work because I also have NT switches.  Your regex doesn't cover all the possible scenarios.

If I change it to exact match my use case, then it works:
`r"-NTR\s*(\d+):(.*):(\d+)"`

**Comment by nojhan** [comment]
What about `-.*[LRD].*` ?

**Comment by netllama** [comment]
Yes, that works.   thanks!

**Comment by nojhan** [comment]
Thanks for having taken time to report and test fixes! I'll do a release of
a consolidated version.

Le sam. 6 août 2022 à 21:09, Lonni J Friedman ***@***.***> a
écrit :

> Yes, that works. thanks!
>
