### ISSUE TITLE
Dependencies: "psutil", and probably "pip"

### ISSUE THREAD

**Issue by Kimael** [nojhan/tunnelmon#4]
Hi!

I downloaded your tunnelmon.py script
and tried to run it (KUbuntu 20.04 LTS); I got this error:

```bash
$ python3 tunnelmon.py 
Traceback (most recent call last):
  File "tunnelmon.py", line 33, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

I "fixed" the situtation by installing "pip" module to easily install module "psutil"
```bash
$> sudo apt install pip
$> python3 -m pip install psutil
```

As you may consider as relevant to add this in your README file
here I am reporting this issue :)

Thanks for the nice tool!

-- 
Mickaël Sibelle

**Comment by nojhan** [comment]
Thanks for noticing!
